# Generated by Django 4.2.5 on 2023-11-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='Kategori',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='menu.kategori'),
            preserve_default=False,
        ),
    ]
