# Generated by Django 4.2.5 on 2023-11-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_produk_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='jumlah',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.CharField(max_length=20),
        ),
    ]
