# Generated by Django 4.2.5 on 2023-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_produk_jumlah_alter_produk_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gmbr_produk',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
